### ISSUE TITLE
Getting errors dialing 

### ISSUE THREAD

**Issue by enishoca** [mo-g/1910calleditwantsitsphoneback#17]
dialed 1 got messages
dialed 2 got the following 
[INFO] Handset lifted.
[INFO] Got digit: 4
Traceback (most recent call last):
  File "/home/pi/1910/phonedaemon/modules/HardwareAbstractionLayer.py", line 88, in dialling_state
    self.callback_digit(self.pulse_table[pulses])
  File "TelephoneDaemon.py", line 180, in digit_dialled
    self.entered_digits += digit
TypeError: cannot concatenate 'str' and 'int' objects
[INFO] Got digit: 4
Traceback (most recent call last):
  File "/home/pi/1910/phonedaemon/modules/HardwareAbstractionLayer.py", line 88, in dialling_state
    self.callback_digit(self.pulse_table[pulses])
  File "TelephoneDaemon.py", line 180, in digit_dialled
    self.entered_digits += digit
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by mo-g** [comment]
Well that's a derp. I did this on a PHP script this morning. No error, but all my text was replaced with 0's.

I like Python's way better.
